import 'dart:io';

void main() async {
  print('🔥 CREATING ADMIN USER FOR MAHRUKH...');
  print('');
  print('📧 Email: mahrukh.tibbi@gmail.com');
  print('🔑 Password: admin123456');
  print('');
  print('⚠️  MANUAL SETUP REQUIRED:');
  print('');
  print('1. Go to: https://console.firebase.google.com');
  print('2. Select your project');
  print('3. Authentication → Users → Add user');
  print('   Email: mahrukh.tibbi@gmail.com');
  print('   Password: admin123456');
  print('   COPY THE UID!');
  print('');
  print('4. Firestore Database → users collection → Add document');
  print('   Document ID: [paste the UID from step 3]');
  print('');
  print('   Add these fields:');
  print('   userID: [paste UID] (string)');
  print('   name: Mahrukh Tibbi (string)');
  print('   email: mahrukh.tibbi@gmail.com (string)');
  print('   role: admin (string)');
  print('   isActive: true (boolean)');
  print('   createdAt: 2024-01-15T10:00:00.000Z (string)');
  print('   permissions: (array with these values:)');
  print('     - createUsers');
  print('     - viewUsers');
  print('     - updateUsers');
  print('     - deleteUsers');
  print('     - createBranches');
  print('     - viewBranches');
  print('     - updateBranches');
  print('     - deleteBranches');
  print('     - createDoctors');
  print('     - viewDoctors');
  print('     - updateDoctors');
  print('     - deleteDoctors');
  print('     - createAppointments');
  print('     - viewAppointments');
  print('     - updateAppointments');
  print('     - deleteAppointments');
  print('     - createServices');
  print('     - viewServices');
  print('     - updateServices');
  print('     - deleteServices');
  print('     - createBookings');
  print('     - viewBookings');
  print('     - updateBookings');
  print('     - deleteBookings');
  print('     - viewReports');
  print('     - viewAnalytics');
  print('');
  print('5. Save the document');
  print('');
  print('6. Go to http://localhost:8080 and login!');
  print('');
  print('✅ DONE! Your admin user will be ready.');
}
