console.log('🔍 DEBUGGING ADMIN SETUP');
console.log('');
console.log('STEP 1: Check Firebase Auth');
console.log('- Go to Firebase Console → Authentication → Users');
console.log('- Look for: mahrukh.tibbi@gmail.com');
console.log('- Copy the UID if it exists');
console.log('');
console.log('STEP 2: Check Firestore');
console.log('- Go to Firestore Database → Data');
console.log('- Look for: users collection');
console.log('- Look for document with the UID from step 1');
console.log('');
console.log('STEP 3: If ANYTHING is missing, do this:');
console.log('');
console.log('A) DELETE any existing mahrukh.tibbi@gmail.com user');
console.log('B) ADD NEW USER:');
console.log('   Email: mahrukh.tibbi@gmail.com');
console.log('   Password: admin123456');
console.log('   >>> COPY THE NEW UID <<<');
console.log('');
console.log('C) CREATE FIRESTORE DOCUMENT:');
console.log('   Collection: users');
console.log('   Document ID: [paste the UID]');
console.log('   Fields:');
console.log('     userID: [paste UID] (string)');
console.log('     name: Mahrukh Tibbi (string)');
console.log('     email: mahrukh.tibbi@gmail.com (string)');
console.log('     role: admin (string)');
console.log('     isActive: true (boolean)');
console.log('     createdAt: 2024-01-15T10:00:00.000Z (string)');
console.log('     permissions: ["createUsers","viewUsers","updateUsers","deleteUsers","createBranches","viewBranches","updateBranches","deleteBranches","createDoctors","viewDoctors","updateDoctors","deleteDoctors","createAppointments","viewAppointments","updateAppointments","deleteAppointments","createServices","viewServices","updateServices","deleteServices","createBookings","viewBookings","updateBookings","deleteBookings","viewReports","viewAnalytics"] (array)');
console.log('');
console.log('D) SAVE and try login again!');
console.log('');
console.log('🎯 The UID MUST match between Auth and Firestore!');
