// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupXEvQhZ-KvajATZKIxOokeDbmi-8p_A',
    appId: '1:562380229586:web:665f526abbd449645c560b',
    messagingSenderId: '562380229586',
    projectId: 'aesthetics-lab-1',
    authDomain: 'aesthetics-lab-1.firebaseapp.com',
    storageBucket: 'aesthetics-lab-1.firebasestorage.app',
    measurementId: 'G-TTDQK7KC7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADEbjg5fhetyE4s6lgfCdCIrmzvOVtenQ',
    appId: '1:562380229586:android:28300ffc60c45dcd5c560b',
    messagingSenderId: '562380229586',
    projectId: 'aesthetics-lab-1',
    storageBucket: 'aesthetics-lab-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKVDkR3XrkBoukKzgqMErYghUh8CxDM0Q',
    appId: '1:562380229586:ios:080f69fee7c65aae5c560b',
    messagingSenderId: '562380229586',
    projectId: 'aesthetics-lab-1',
    storageBucket: 'aesthetics-lab-1.firebasestorage.app',
    iosBundleId: 'com.example.aestheticsLabsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKVDkR3XrkBoukKzgqMErYghUh8CxDM0Q',
    appId: '1:562380229586:ios:080f69fee7c65aae5c560b',
    messagingSenderId: '562380229586',
    projectId: 'aesthetics-lab-1',
    storageBucket: 'aesthetics-lab-1.firebasestorage.app',
    iosBundleId: 'com.example.aestheticsLabsAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAupXEvQhZ-KvajATZKIxOokeDbmi-8p_A',
    appId: '1:562380229586:web:7ec46844ee543aa25c560b',
    messagingSenderId: '562380229586',
    projectId: 'aesthetics-lab-1',
    authDomain: 'aesthetics-lab-1.firebaseapp.com',
    storageBucket: 'aesthetics-lab-1.firebasestorage.app',
    measurementId: 'G-M4M3NJNQ01',
  );
}
